[build]
  base = "dashboard"
  command = "npm run sources && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "24"
  
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "cross-origin"
