[build]
  publish = "dashboard/build"
  command = "echo 'Using prebuilt site'"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "cross-origin"

[[redirects]]
  from = "/api/null/*"
  to = "/api/:splat"
  status = 200
